### ISSUE TITLE
RxDebug and Java code

### ISSUE THREAD

**Issue by exitoso** [SumeraMartin/RxDebug#29]
How use RxDebug with code written on Java?

**Comment by SumeraMartin** [comment]
Hi, since RxDebug is written in kotlin as an extension function, it is possible to execute it as a static method.

```
RxDebugExtensionsKt.debug(
    Observable.just(1, 2, 3).filter(it -> it > 2)
).subscribe();
```

But it doesn't look as nice as for Kotlin :-/

**Comment by exitoso** [comment]
Many thanks!
